#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dri3proto
Version  : 1.0
Release  : 4
URL      : http://xorg.freedesktop.org/releases/individual/proto/dri3proto-1.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/dri3proto-1.0.tar.gz
Summary  : DRI3 extension headers
Group    : Development/Tools
License  : HPND
Requires: dri3proto-doc
BuildRequires : pkgconfig(xorg-macros)

%description
No detailed description available

%package dev
Summary: dev components for the dri3proto package.
Group: Development

%description dev
dev components for the dri3proto package.


%package doc
Summary: doc components for the dri3proto package.
Group: Documentation

%description doc
doc components for the dri3proto package.


%prep
%setup -q -n dri3proto-1.0

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/dri3proto.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/dri3proto/*
